version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "angularjs",
    "angular",
    "react",
    "vue",
    "ember",
    "meteor"
  ]
  environment = [
    "jasmine",
    "vitest",
    "jest",
    "mocha",
    "cypress",
    "mongo",
    "browser",
    "nodejs",
    "jquery"
  ]

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "8"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "docker"

  [analyzers.meta]
  dockerfile_paths = ["./"]

[[transformers]]
name = "standardjs"

[[transformers]]
name = "prettier"