trigger:
- master

pool:
  name: agents

stages:
  - stage: Tools
    jobs:
      - job: Installer
        displayName: Installing the tools
        steps:
          - task: Maven@4
            inputs:
              mavenPomFile: 'pom.xml'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false
              goals: 'package'
#          - script: |
#              apt-get update
#              apt-get install openjdk-8-jdk -y
#              apt install maven -y
      - job: Build
        displayName: Building Artifacts
        dependsOn: Installer
        steps:
          - script: |
              mvn clean package
              ls -la
  - stage: Test
    jobs: 
      - job: unit_test
        displayName: Performing unit test
        steps:
          - script: | 
              mvn test
              ls -la
  - stage: OWASP
    jobs:
      - job: Dependency_Check
        displayName: Checking the dependency
        steps:
          - task: dependency-check-build-task@6
            inputs:
              projectName: 'Spring-boot-HW'
              scanPath: '**/target/*.jar'
              format: 'JUNIT'

              


