trigger:
- master

pool:
  name: agents

stages:
  - stage: Tools
    jobs:
      - job: Installer
        displayName: Installing the tools
        steps:
          - script: |
              apt-get update
              apt-get install openjdk-8-jdk -y
              apt install maven -y
      - job: Build
        displayName: Building Artifacts
        dependsOn: Installer
        steps:
          - script: |
              mvn clean package
              ls -la
              ls -la target

              


