trigger:
- feature-4.0

pool:
  name: agents

variables:
  - template: "vars.yml"
  - group: manifest-git

stages:
  - stage: Build_Test
    jobs:
      - job: gitleaks_SBOM
        displayName: Detect secrets & Generate SBOM
        steps:
          - task: Gitleaks@2
            inputs:
              scanlocation: '$(Build.SourcesDirectory)'
              configtype: 'predefined'
              predefinedconfigfile: 'GitleaksUdmCombo.toml'
              scanmode: 'nogit'
              redact: false
              taskfail: false
              reportformat: 'sarif'
          - script: |
              curl -Lo $(Agent.TempDirectory)/sbom-tool https://github.com/microsoft/sbom-tool/releases/latest/download/sbom-tool-linux-x64
              chmod +x $(Agent.TempDirectory)/sbom-tool
              $(Agent.TempDirectory)/sbom-tool generate -b $(Build.ArtifactStagingDirectory) -bc $(Build.SourcesDirectory) -pn Test -pv 1.0.0 -ps MyCompany -nsb https://sbom.mycompany.com -V Verbose
          
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'sbom'
              publishLocation: 'Container'

      - job: Artifact_Build
        displayName: Testing & Building artifacts
        dependsOn: gitleaks_SBOM
        steps:
          - task: Maven@4
            inputs:
              mavenPomFile: 'pom.xml'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false
          - script: |
              ls -la
              ls -la target
              
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(Build.SourcesDirectory)'
              Contents: '**/target/*.jar'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'springapp'
              publishLocation: 'Container'

      - job: Dependency_Check
        displayName: Checking the dependency
        dependsOn: Artifact_Build
        steps:
          - checkout: none
          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'springapp'
              downloadPath: '$(System.ArtifactsDirectory)'
          - task: dependency-check-build-task@6
            inputs:
              projectName: 'spring-app'
              scanPath: '**/target/*.jar'
              format: 'JUNIT'

          - task: PublishTestResults@2
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: 'dependency-check/*junit.xml'
              searchFolder: '$(Common.TestResultsDirectory)'
              testRunTitle: 'Dependency Check'
  - stage: Deployment
    jobs:
      - job: Docker_build
        displayName: Building Docker image
        steps:
          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: 'current'
              downloadType: 'specific'
              artifactName: springapp
              downloadPath: '$(Build.SourcesDirectory)'
              
          - script: ls -la
          - task: Docker@2
            inputs:
              containerRegistry: 'docker-registry'
              repository: 'shmdus/springapp'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              tags: '$(major).$(Build.BuildId)'
      - job: Manifest_Update
        displayName: updating the manifest file
        dependsOn: Docker_build
        steps:
          - script: |
              git clone https://$(gituser):$(gittoken)@dev.azure.com/shaikmhd95786/Apps/_git/manifest
              cd manifest
              git config --global user.name "$(gituser)"
              git config --global user.email "$(gitmail)"
              sed -i 's|$(dockeruser).*|$(repo):$(major).$(Build.BuildId)|g' deployment.yaml
              cat deployment.yaml
              git add .
              git commit -m "image updated"
              git push -uf origin
          

          

              


