trigger:
- master

pool:
  name: agents

stages:
  - stage: Build_Test
    jobs:
      - job: Artifact_Build
        displayName: Testing & Building artifacts
        steps:
          - task: Maven@4
            inputs:
              mavenPomFile: 'pom.xml'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false

          - script: |
              ls -la target

      - job: Dependency_Check
        displayName: Checking the dependency
        dependsOn: Artifact_Build
        steps:
          - task: dependency-check-build-task@6
            inputs:
              projectName: 'spring-app'
              scanPath: '**/target/*.jar'
              format: 'JUNIT'
          - script: ls -la target

              


