trigger:
- master

pool:
  name: agents

variables:
  - template: "vars.yml"
  - group: manifest-git


steps:
  - script: |
      git clone https://$(gituser):$(gittoken)@dev.azure.com/shaikmhd95786/Apps/_git/manifest
      cd manifest
      git config --global user.name "$(gituser)"
      git config --global user.email "$(gitmail)"
      sed -i 's|$(dockeruser).*|$(repo):$(major).$(Build.BuildId)|g' deployment.yaml
      git add .
      git commit -m "image updated"
      git push origin -o ci-skip
          

          

              


