trigger:
- master

pool:
  name: agents

stages:
  - stage: Build_Test
    jobs:
      - job: Artifact_Build
        displayName: Installing the tools
        steps:
          - task: Maven@4
            inputs:
              mavenPomFile: 'pom.xml'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false

#          - script: |
#              apt-get update
#              apt-get install openjdk-8-jdk -y
#              apt install maven -y

  - stage: Code_Analysis
    jobs:
      - job: Dependency_Check
        displayName: Checking the dependency
        steps:
          - task: dependency-check-build-task@6
            inputs:
              projectName: 'Spring-boot-HW'
              scanPath: '**/target/*.jar'
              format: 'JUNIT'

              


