apiVersion: apps/v1
kind: Deployment
metadata:
  name: superapp
  labels:
    app: spring
spec:
  selector:
    matchLabels:
      app: spring
  replicas: 2
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
        - name: springapp
          image: shmdus/springapp
          ports:
            - containerPort: 8080