apiVersion: v1
kind: Service
metadata:
  name: springapp-svc
spec:
  selector:
    app: react
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32000
