#Springboot-jdk-11
name: product
on: workflow_dispatch
env:
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASS: ${{ secrets.DB_PASS }}
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_PORT: ${{ secrets.DB_PORT }}
jobs:
  build:
    uses: superinfo/cicd-reusables/.github/workflows/springboot-jdk-11.yaml@main
