#Springboot-jdk-11
name: product
on: workflow_dispatch
env:
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASS: ${{ secrets.DB_PASS }}
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_PORT: ${{ secrets.DB_PORT }}
permissions:
   checks: write
   security-events: write
   pull-requests: write 

jobs:      
   secret:
     runs-on: ubuntu-latest
     outputs:
       appfile: ${{steps.app.outputs.app}}
     steps:
       - name: checkout
         uses: actions/checkout@v4.1.1
       - name: env
         id: app
         run: echo "app=$(basename ${{github.repository}})" >> $GITHUB_OUTPUT
       - name: test
         env:
           appname: ${{steps.app.outputs.name}}
         run: |
           echo $appname
         
   sbom:
      needs: secret
      runs-on: ubuntu-latest
      steps:
        - name: run
          env:
            APP_NAME: ${{ needs.outputs.appfile }}
            super: $(basename ${{github.respoitory}})
          run:
            echo $APP_NAME
            echo $(env.APP_NAME)
            echo $(APP_NAME)
            echo $appname
            echo $super
            
            
            
          

          
    # #  - name: JaCoCo Report
    # #    uses: Madrapps/jacoco-report@v1.6.1
    # #    with:
    # #      paths: target/site/jacoco/jacoco.xml
    # #      token: ${{secrets.TOKEN_REPO}}
    # #      min-coverage-overall: 60
      

    
