#Springboot-jdk-11
name: product
on: workflow_dispatch
env:
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASS: ${{ secrets.DB_PASS }}
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_PORT: ${{ secrets.DB_PORT }}
permissions:
   checks: write
   security-events: write
   pull-requests: write 

jobs:
  settings:
    runs-on: ubuntu-latest
    outputs:
      appenv: ${{ steps.app.outputs.app-name }}
    steps:
       - name: setting env
         id: app
         run: echo "app-name=$(basename ${{ github.repository }})"
       
  CICD:
    needs: settings
    uses: super-info/cicd-reusable/.github/workflows/springboot-jdk-11.yaml@main
    with:
      google_project_id: ${{ vars.GOOGLE_PROJECT_ID }}
      #tag: ${{ github.run_number }}
      
      
    secrets:
      gitguradian_api_key: ${{ secrets.GITGUARDIAN_API_KEY }}
      sonar_token: ${{ secrets.SONAR_TOKEN }}
      git_token: ${{ secrets.GIT_TOKEN }}
      git_mail: ${{ secrets.GIT_MAIL }}
      google_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
