#Springboot-jdk-11
name: product
on: workflow_dispatch
env:
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASS: ${{ secrets.DB_PASS }}
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_PORT: ${{ secrets.DB_PORT }}
permissions:
   checks: write
   security-events: write
   pull-requests: write 

jobs:      
   secret:
     runs-on: ubuntu-latest
     outputs:
       appfile: ${{steps.app.outputs.appenv}}
     steps:
       - name: checkout
         uses: actions/checkout@v4.1.1
       - name: env
         id: app
         run: echo "appenv=$(basename ${{github.repository}})" >> $GITHUB_OUTPUT
       - name: test
         env:
           appname: ${{ steps.app.outputs.appenv }}
         run: |
           echo $appname
         
   sbom:
      needs: secret
      runs-on: ubuntu-latest
      steps:
        - name: run
          env:
            APP_NAME: ${{ needs.secret.outputs.appfile }}
            super: $(basename ${{github.respoitory}})
          run: |
           # echo "NAME_APP=${{ needs.secret.outputs.appfile }}" >> $GITHUB_ENV
            echo "$NAME_APP"
            echo "Ths is my $APP_NAME"
            echo "Ths is $(env.APP_NAME)"
            echo "testing $super"

            
   test:
     needs: [sbom, secret]
     runs-on: ubuntu-latest
     steps:
       - name: testing
         env:
           APP_NAME: ${{ jobs.secret.outputs.appfile }}
           appname: ${{ jobs.steps.app.appname }}
           ap_name: ${{ needs.secret.outputs.appfile }}
         run: |
           echo "this is $APP_NAME"
           echo $APP_NAME
           echo $appname
           echo $ap_name
   #     - name: checking
   #       run: 
          
            
            
            
          

          
    # #  - name: JaCoCo Report
    # #    uses: Madrapps/jacoco-report@v1.6.1
    # #    with:
    # #      paths: target/site/jacoco/jacoco.xml
    # #      token: ${{secrets.TOKEN_REPO}}
    # #      min-coverage-overall: 60
      

    
